[package]
name = "xulo-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "xulo"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rustyline = { workspace = true }
xulo-core = { workspace = true }
xulo-lexer = { workspace = true }
xulo-parser = { workspace = true }
xulo-semantic = { workspace = true }
xulo-runtime = { workspace = true }
xulo-compiler = { workspace = true }
xulo-ide = { workspace = true }
xulo-framework = { workspace = true }

[features]
default = []
webview = ["xulo-framework/webview"]

[dev-dependencies]
