[package]
name = "xulo-runtime"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
xulo-core = { workspace = true }
corosensei = "0.2"

[dev-dependencies]
xulo-lexer = { workspace = true }
xulo-parser = { workspace = true }
xulo-semantic = { workspace = true }
