use std::ops::Range;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Token {
    Ident,
    Fn,
    Let,
    Const,
    Return,
    If,
    Else,
    For,
    In,
    Print,
    Type,
    Enum,
    Null,
    Number,
    String,
    Boolean,
    Colon,
    DoubleColon,
    Semicolon,
    Comma,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Assign,
    Plus,
    Minus,
    Star,
    Slash,
    Eq,
    Neq,
    Lt,
    Gt,
    Lte,
    Gte,
    Arrow,
    Pipe,
    Amp,
    Question,
    Bang,
    Dot,
    QuestionDot,
    Nullish,
    RangeOp,
    Ellipsis,
    While,
    Match,
    And,
    Or,
    Async,
    Await,
    Try,
    Catch,
    Throw,
    Import,
    Export,
    Pub,
    From,
    As,
    Default,
    /// A reserved-for-future-use word (see `RESERVED_WORDS`): it lexes as a
    /// token instead of an identifier so it can never be used as a name.
    Reserved,
    At,
    Dollar,
    EOF,
}

/// Words reserved for future language features. They are not keywords yet, but
/// can never be used as identifiers (checked in `from_keyword`), keeping the
/// door open for later syntax without breaking reserved-word code.
pub const RESERVED_WORDS: &[&str] = &[
    "abstract",
    "actor",
    "arguments",
    "associatedtype",
    "bench",
    "break",
    "case",
    "cfg",
    "channel",
    "class",
    "continue",
    "debugger",
    "defer",
    "deinit",
    "delete",
    "derive",
    "doc",
    "do",
    "eval",
    "extension",
    "fallthrough",
    "final",
    "finally",
    "function",
    "generic",
    "generator",
    "global",
    "guard",
    "impl",
    "init",
    "instanceof",
    "interface",
    "isolated",
    "iterator",
    "lazy",
    "library",
    "local",
    "macro",
    "meta",
    "module",
    "move",
    "mut",
    "new",
    "open",
    "override",
    "package",
    "priv",
    "protocol",
    "receiver",
    "ref",
    "rethrows",
    "select",
    "self",
    "sender",
    "spawn",
    "static",
    "struct",
    "super",
    "switch",
    "task",
    "this",
    "trait",
    "typealias",
    "unowned",
    "unsafe",
    "use",
    "virtual",
    "weak",
    "where",
    "with",
    "var",
    "void",
    "yield",
];

impl Token {
    /// Map a keyword / type-name string to its token. Returns `None` for
    /// ordinary identifiers.
    pub fn from_keyword(s: &str) -> Option<Token> {
        Some(match s {
            "fn" => Token::Fn,
            "let" => Token::Let,
            "const" => Token::Const,
            "return" => Token::Return,
            "if" => Token::If,
            "else" => Token::Else,
            "for" => Token::For,
            "in" => Token::In,
            "print" => Token::Print,
            "type" => Token::Type,
            "enum" => Token::Enum,
            "null" => Token::Null,
            "while" => Token::While,
            "match" => Token::Match,
            "and" => Token::And,
            "or" => Token::Or,
            "async" => Token::Async,
            "await" => Token::Await,
            "try" => Token::Try,
            "catch" => Token::Catch,
            "throw" => Token::Throw,
            "import" => Token::Import,
            "export" => Token::Export,
            "pub" => Token::Pub,
            "from" => Token::From,
            "as" => Token::As,
            "default" => Token::Default,
            "true" | "false" => Token::Boolean,
            _ => {
                // A reserved word is not a keyword yet, but it is already
                // forbidden as an identifier (docs §lexical). The set is the
                // union of the "future keywords" table and the alphabetical
                // reserved list; `_` stays a wildcard identifier instead.
                if RESERVED_WORDS.contains(&s) {
                    return Some(Token::Reserved);
                }
                return None;
            }
        })
    }

    pub fn describe(&self) -> &'static str {
        match self {
            Token::Ident => "identifier",
            Token::Fn => "`fn`",
            Token::Let => "`let`",
            Token::Const => "`const`",
            Token::Return => "`return`",
            Token::If => "`if`",
            Token::Else => "`else`",
            Token::For => "`for`",
            Token::In => "`in`",
            Token::Print => "`print`",
            Token::Type => "`type`",
            Token::Enum => "`enum`",
            Token::Null => "`null`",
            Token::While => "`while`",
            Token::Match => "`match`",
            Token::And => "`and`",
            Token::Or => "`or`",
            Token::Async => "`async`",
            Token::Await => "`await`",
            Token::Try => "`try`",
            Token::Catch => "`catch`",
            Token::Throw => "`throw`",
            Token::Import => "`import`",
            Token::Export => "`export`",
            Token::Pub => "`pub`",
            Token::From => "`from`",
            Token::As => "`as`",
            Token::Default => "`default`",
            Token::Reserved => "`<reserved keyword>`",
            Token::At => "`@`",
            Token::Dollar => "`$`",
            Token::Number => "number",
            Token::String => "string",
            Token::Boolean => "boolean",
            Token::Colon => "`:`",
            Token::DoubleColon => "`::`",
            Token::Semicolon => "`;`",
            Token::Comma => "`,`",
            Token::LParen => "`(`",
            Token::RParen => "`)`",
            Token::LBrace => "`{`",
            Token::RBrace => "`}`",
            Token::LBracket => "`[`",
            Token::RBracket => "`]`",
            Token::Assign => "`=`",
            Token::Plus => "`+`",
            Token::Minus => "`-`",
            Token::Star => "`*`",
            Token::Slash => "`/`",
            Token::Eq => "`==`",
            Token::Neq => "`!=`",
            Token::Lt => "`<`",
            Token::Gt => "`>`",
            Token::Lte => "`<=`",
            Token::Gte => "`>=`",
            Token::Arrow => "`=>`",
            Token::Pipe => "`|`",
            Token::Amp => "`&`",
            Token::Question => "`?`",
            Token::Bang => "`!`",
            Token::Dot => "`.`",
            Token::QuestionDot => "`?.`",
            Token::Nullish => "`??`",
            Token::RangeOp => "`..<`",
            Token::Ellipsis => "`...`",
            Token::EOF => "end of file",
        }
    }
}

/// A token annotated with its byte span in the source file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LexedToken {
    pub kind: Token,
    pub text: String,
    pub span: Range<usize>,
}

impl LexedToken {
    pub fn new(kind: Token, text: impl Into<String>, span: Range<usize>) -> Self {
        Self {
            kind,
            text: text.into(),
            span,
        }
    }
}
