[package]
name = "xulo-compiler"
version.workspace = true
edition.workspace = true

[dependencies]
xulo-core = { workspace = true }
xulo-lexer = { workspace = true }
xulo-parser = { workspace = true }
xulo-semantic = { workspace = true }
xulo-runtime = { workspace = true }
cranelift = "0.110"
cranelift-frontend = "0.110"
cranelift-module = "0.110"
cranelift-jit = "0.110"
cranelift-object = "0.110"
cranelift-native = "0.110"
target-lexicon = "0.13"

[dev-dependencies]
