use std::ops::Range;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Token {
    Ident,
    Fn,
    Let,
    Const,
    Return,
    If,
    Else,
    For,
    In,
    Print,
    Type,
    Enum,
    Null,
    Number,
    String,
    Boolean,
    Colon,
    DoubleColon,
    Semicolon,
    Comma,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Assign,
    Plus,
    Minus,
    Star,
    Slash,
    Eq,
    Neq,
    Lt,
    Gt,
    Lte,
    Gte,
    Arrow,
    Pipe,
    Amp,
    Question,
    Bang,
    Dot,
    QuestionDot,
    Nullish,
    RangeOp,
    Ellipsis,
    While,
    Match,
    And,
    Or,
    Async,
    Await,
    Try,
    Catch,
    Throw,
    Import,
    Export,
    From,
    As,
    Default,
    At,
    Dollar,
    EOF,
}

impl Token {
    /// Map a keyword / type-name string to its token. Returns `None` for
    /// ordinary identifiers.
    pub fn from_keyword(s: &str) -> Option<Token> {
        Some(match s {
            "fn" => Token::Fn,
            "let" => Token::Let,
            "const" => Token::Const,
            "return" => Token::Return,
            "if" => Token::If,
            "else" => Token::Else,
            "for" => Token::For,
            "in" => Token::In,
            "print" => Token::Print,
            "type" => Token::Type,
            "enum" => Token::Enum,
            "null" => Token::Null,
            "while" => Token::While,
            "match" => Token::Match,
            "and" => Token::And,
            "or" => Token::Or,
            "async" => Token::Async,
            "await" => Token::Await,
            "try" => Token::Try,
            "catch" => Token::Catch,
            "throw" => Token::Throw,
            "import" => Token::Import,
            "export" => Token::Export,
            "from" => Token::From,
            "as" => Token::As,
            "default" => Token::Default,
            "true" | "false" => Token::Boolean,
            _ => return None,
        })
    }

    pub fn describe(&self) -> &'static str {
        match self {
            Token::Ident => "identifier",
            Token::Fn => "`fn`",
            Token::Let => "`let`",
            Token::Const => "`const`",
            Token::Return => "`return`",
            Token::If => "`if`",
            Token::Else => "`else`",
            Token::For => "`for`",
            Token::In => "`in`",
            Token::Print => "`print`",
            Token::Type => "`type`",
            Token::Enum => "`enum`",
            Token::Null => "`null`",
            Token::While => "`while`",
            Token::Match => "`match`",
            Token::And => "`and`",
            Token::Or => "`or`",
            Token::Async => "`async`",
            Token::Await => "`await`",
            Token::Try => "`try`",
            Token::Catch => "`catch`",
            Token::Throw => "`throw`",
            Token::Import => "`import`",
            Token::Export => "`export`",
            Token::From => "`from`",
            Token::As => "`as`",
            Token::Default => "`default`",
            Token::At => "`@`",
            Token::Dollar => "`$`",
            Token::Number => "number",
            Token::String => "string",
            Token::Boolean => "boolean",
            Token::Colon => "`:`",
            Token::DoubleColon => "`::`",
            Token::Semicolon => "`;`",
            Token::Comma => "`,`",
            Token::LParen => "`(`",
            Token::RParen => "`)`",
            Token::LBrace => "`{`",
            Token::RBrace => "`}`",
            Token::LBracket => "`[`",
            Token::RBracket => "`]`",
            Token::Assign => "`=`",
            Token::Plus => "`+`",
            Token::Minus => "`-`",
            Token::Star => "`*`",
            Token::Slash => "`/`",
            Token::Eq => "`==`",
            Token::Neq => "`!=`",
            Token::Lt => "`<`",
            Token::Gt => "`>`",
            Token::Lte => "`<=`",
            Token::Gte => "`>=`",
            Token::Arrow => "`=>`",
            Token::Pipe => "`|`",
            Token::Amp => "`&`",
            Token::Question => "`?`",
            Token::Bang => "`!`",
            Token::Dot => "`.`",
            Token::QuestionDot => "`?.`",
            Token::Nullish => "`??`",
            Token::RangeOp => "`..<`",
            Token::Ellipsis => "`...`",
            Token::EOF => "end of file",
        }
    }
}

/// A token annotated with its byte span in the source file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LexedToken {
    pub kind: Token,
    pub text: String,
    pub span: Range<usize>,
}

impl LexedToken {
    pub fn new(kind: Token, text: impl Into<String>, span: Range<usize>) -> Self {
        Self {
            kind,
            text: text.into(),
            span,
        }
    }
}
